
// This is an autogenerated file from Firebase Studio.
"use client";

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Newspaper, ChevronsDown } from 'lucide-react';
import { useState, useMemo } from 'react'; 
import { Input } from '@/components/ui/input'; 

interface NewsArticle {
  id: string;
  title: string;
  summary: string;
  imageUrl: string;
  dataAiHint: string;
  publicationDate: string;
  source: string;
  articleUrl: string; 
}

const ARTICLES_PER_LOAD = 3; // Number of articles to load at a time

const allNewsArticles: NewsArticle[] = [
  {
    id: 'new-species-discovery-2025',
    title: 'Descubren Nueva Especie Bioluminiscente en la Fosa de las Marianas',
    summary: 'Científicos anuncian el hallazgo de una nueva especie de pez abisal que emite una luz azul intensa, adaptada a la oscuridad total de las profundidades marinas. El descubrimiento abre nuevas vías de investigación sobre la vida en condiciones extremas.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'deep sea fish',
    publicationDate: '25 de Febrero, 2025',
    source: 'Instituto Oceanográfico Global',
    articleUrl: '/news/new-species-discovery-2025',
  },
  {
    id: 'plastic-cleanup-pacific-2025',
    title: 'Innovador Sistema de Limpieza de Plásticos Muestra Resultados Prometedores en el Pacífico',
    summary: 'Un nuevo sistema autónomo de recolección de plásticos ha superado las pruebas iniciales, retirando varias toneladas de desechos del Gran Parche de Basura del Pacífico en su primer mes de operación.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ocean cleanup',
    publicationDate: '10 de Marzo, 2025',
    source: 'Tecnología Marina Limpia Hoy',
    articleUrl: '/news/plastic-cleanup-pacific-2025',
  },
  {
    id: 'coral-reef-recovery-caribbean-2025',
    title: 'Arrecifes de Coral del Caribe Muestran Signos de Recuperación Gracias a Esfuerzos de Restauración',
    summary: 'Proyectos de restauración de coral a gran escala en el Caribe están dando frutos, con un notable aumento en la cobertura de coral vivo y la biodiversidad asociada, según un estudio reciente.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'coral reef restoration',
    publicationDate: '5 de Abril, 2025',
    source: 'Conservación Coralina Internacional',
    articleUrl: '/news/coral-reef-recovery-caribbean-2025',
  },
  {
    id: 'ocean-acidification-impact-2025',
    title: 'Nuevo Estudio Revela Impactos Acelerados de la Acidificación Oceánica en Moluscos',
    summary: 'Una investigación publicada hoy advierte que la acidificación de los océanos está afectando a las poblaciones de moluscos a un ritmo más rápido de lo previsto, amenazando las cadenas alimentarias marinas.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'ocean acidification',
    publicationDate: '18 de Mayo, 2025',
    source: 'Revista Científica Marina',
    articleUrl: '/news/ocean-acidification-impact-2025',
  },
  {
    id: 'new-ocean-tech-2025',
    title: 'Tecnología Revolucionaria Permite Comunicación con Delfines',
    summary: 'Un equipo de científicos ha desarrollado un dispositivo que traduce los silbidos de los delfines a lenguaje humano, abriendo nuevas fronteras en la comunicación inter-especies.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'dolphin communication',
    publicationDate: '15 de Junio, 2025',
    source: 'Avances en Bioacústica Marina',
    articleUrl: '/news/new-ocean-tech-2025',
  },
  {
    id: 'underwater-volcano-discovery-2025',
    title: 'Descubren Volcán Submarino Activo Cerca de las Costas de Japón',
    summary: 'Una expedición oceanográfica ha confirmado la existencia de un volcán submarino previamente desconocido que muestra signos de actividad reciente, lo que podría impactar la geología local.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'underwater volcano',
    publicationDate: '28 de Junio, 2025',
    source: 'Centro Geológico del Pacífico',
    articleUrl: '/news/underwater-volcano-discovery-2025',
  },
   {
    id: 'marine-protected-area-expansion-2025',
    title: 'Expansión Global de Áreas Marinas Protegidas Supera Objetivos',
    summary: 'Un informe internacional confirma que la expansión de áreas marinas protegidas ha superado los objetivos para 2025, aunque se necesita más trabajo para asegurar su efectividad.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'marine protection',
    publicationDate: '10 de Julio, 2025',
    source: 'ONU Medio Ambiente',
    articleUrl: '/news/marine-protected-area-expansion-2025',
  },
  {
    id: 'whale-migration-patterns-shift-2025',
    title: 'Cambios en Patrones Migratorios de Ballenas Preocupan a Científicos',
    summary: 'Nuevos datos satelitales muestran alteraciones significativas en las rutas migratorias de varias especies de ballenas, posiblemente debido al cambio climático.',
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'whale migration',
    publicationDate: '22 de Julio, 2025',
    source: 'Sociedad de Conservación Marina',
    articleUrl: '/news/whale-migration-patterns-shift-2025',
  }
];

export default function NewsPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [visibleArticleCount, setVisibleArticleCount] = useState(ARTICLES_PER_LOAD);

  const searchFilteredArticles = useMemo(() => {
    return allNewsArticles.filter(article =>
      article.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      article.summary.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [searchTerm]);

  const displayedArticles = useMemo(() => {
    return searchFilteredArticles.slice(0, visibleArticleCount);
  }, [searchFilteredArticles, visibleArticleCount]);

  const handleLoadMore = () => {
    setVisibleArticleCount(prevCount => prevCount + ARTICLES_PER_LOAD);
  };

  const canLoadMore = visibleArticleCount < searchFilteredArticles.length;

  return (
    <div className="container mx-auto px-4 py-12">
      <header className="text-center mb-12">
        <div className="inline-flex items-center justify-center bg-primary/10 p-3 rounded-full mb-4">
          <Newspaper className="h-10 w-10 text-primary" />
        </div>
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl">
          Noticias del Océano
        </h1>
        <p className="mt-3 text-lg text-muted-foreground sm:mt-5 sm:text-xl">
          Mantente al día con los últimos acontecimientos y descubrimientos del mundo marino.
        </p>
      </header>

      <div className="mb-8 max-w-xl mx-auto">
        <Input
          type="text"
          placeholder="Buscar noticias por título o resumen..."
          value={searchTerm}
          onChange={(e) => {
            setSearchTerm(e.target.value);
            setVisibleArticleCount(ARTICLES_PER_LOAD); // Reset count on new search
          }}
          className="w-full text-base shadow-sm"
        />
      </div>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-1"> {/* Single column for better readability */}
        {displayedArticles.length > 0 ? (
          displayedArticles.map((article, index) => (
            <Card
              key={article.id}
              className="flex flex-col md:flex-row rounded-xl shadow-lg transition-all duration-300 hover:shadow-2xl overflow-hidden animate-in fade-in slide-in-from-bottom-5 duration-500 ease-out"
              style={{ animationDelay: `${index * 100}ms` }}
            >
              <div className="md:w-1/3 h-48 md:h-auto overflow-hidden">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={article.imageUrl}
                  alt={article.title}
                  className="w-full h-full object-cover transition-transform duration-300 hover:scale-105"
                  data-ai-hint={article.dataAiHint}
                />
              </div>
              <div className="md:w-2/3 flex flex-col">
                <CardHeader className="p-6">
                  <CardTitle className="text-xl font-semibold hover:text-primary transition-colors">
                    <Link href={article.articleUrl}>{article.title}</Link>
                  </CardTitle>
                  <CardDescription className="text-xs text-muted-foreground pt-1">
                    Publicado el {article.publicationDate} por {article.source}
                  </CardDescription>
                </CardHeader>
                <CardContent className="flex-grow p-6 pt-0">
                  <p className="text-sm text-muted-foreground line-clamp-3">
                    {article.summary}
                  </p>
                </CardContent>
                <CardFooter className="p-6 pt-0">
                  <Button asChild variant="outline" size="sm">
                    <Link href={article.articleUrl}>Leer Más</Link>
                  </Button>
                </CardFooter>
              </div>
            </Card>
          ))
        ) : (
          <p className="text-center text-muted-foreground col-span-full py-10 text-lg">
            {searchTerm ? `No se encontraron noticias que coincidan con "${searchTerm}".` : "No hay noticias para mostrar."}
          </p>
        )}
      </div>

      {canLoadMore && (
        <div className="mt-12 text-center">
          <Button onClick={handleLoadMore} variant="outline" size="lg">
            <ChevronsDown className="mr-2 h-5 w-5" />
            Cargar Más Noticias
          </Button>
        </div>
      )}

      <div className="mt-16 text-center">
        <Button asChild variant="link">
          <Link href="/">Volver a la Página Principal</Link>
        </Button>
      </div>
    </div>
  );
}

