
// This is an autogenerated file from Firebase Studio.
"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle, Crown, Zap } from "lucide-react";
import Link from "next/link";

interface PlanFeature {
  text: string;
  available: boolean;
}

interface Plan {
  id: string;
  title: string;
  description: string;
  price: string;
  pricePeriod: string;
  features: PlanFeature[];
  cta: string;
  highlight?: boolean;
  icon?: React.ReactNode;
}

const plans: Plan[] = [
  {
    id: "bronze",
    title: "Caballito de Mar Bronce",
    description: "Comienza con funciones esenciales de la plataforma.",
    price: "$5",
    pricePeriod: "/ mes",
    features: [
      { text: "Hasta 1,000 consultas/mes", available: true },
      { text: "Velocidad estándar", available: true },
      { text: "Historial básico de actividad", available: true },
      { text: "Soporte por correo electrónico", available: true },
      { text: "Soporte prioritario", available: false },
      { text: "Acceso a nuevas funciones (beta)", available: false },
    ],
    cta: "Elegir Bronce",
    icon: <CheckCircle className="h-6 w-6 text-primary" />,
  },
  {
    id: "silver",
    title: "Delfín de Plata",
    description: "Más acceso y rendimiento mejorado.",
    price: "$15",
    pricePeriod: "/ mes",
    features: [
      { text: "Hasta 10,000 consultas/mes", available: true },
      { text: "Velocidad mejorada", available: true },
      { text: "Historial detallado de actividad", available: true },
      { text: "Soporte prioritario por correo electrónico", available: true },
      { text: "Soporte prioritario", available: true },
      { text: "Acceso a nuevas funciones (beta)", available: false },
    ],
    cta: "Elegir Plata",
    highlight: true,
    icon: <Zap className="h-6 w-6 text-accent" />,
  },
  {
    id: "gold",
    title: "Ballena de Oro",
    description: "La experiencia definitiva para usuarios avanzados.",
    price: "$30",
    pricePeriod: "/ mes",
    features: [
      { text: "Consultas ilimitadas", available: true },
      { text: "Velocidad ultrarrápida", available: true },
      { text: "Historial completo de actividad y análisis", available: true },
      { text: "Soporte prioritario 24/7", available: true },
      { text: "Soporte prioritario", available: true },
      { text: "Acceso anticipado a nuevas funciones (beta)", available: true },
    ],
    cta: "Elegir Oro",
    icon: <Crown className="h-6 w-6 text-accent" />, // Changed from text-yellow-500
  },
];

export default function PremiumPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <header className="text-center mb-12">
        <h1 className="text-4xl font-bold tracking-tight text-primary sm:text-5xl">
          Desbloquea Funciones Premium de MTM
        </h1>
        <p className="mt-3 text-lg text-muted-foreground sm:mt-5 sm:text-xl">
          Elige un plan que se adapte a tus necesidades y mejora tu experiencia en MTM.
        </p>
      </header>

      <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
        {plans.map((plan, index) => (
          <Card
            key={plan.id}
            className={`flex flex-col rounded-xl shadow-lg transition-all duration-300 hover:shadow-2xl animate-in fade-in slide-in-from-bottom-5 duration-500 ease-out ${
              plan.highlight ? "border-2 border-accent ring-2 ring-accent/50" : "border-border"
            }`}
            style={{ animationDelay: `${index * 100}ms` }}
          >
            <CardHeader className="p-6">
              <div className="flex items-center justify-between mb-2">
                <CardTitle className="text-2xl font-semibold">{plan.title}</CardTitle>
                {plan.icon}
              </div>
              <CardDescription className="text-sm text-muted-foreground h-10">
                {plan.description}
              </CardDescription>
            </CardHeader>
            <CardContent className="flex-grow p-6">
              <div className="mb-6">
                <span className="text-4xl font-extrabold text-foreground">{plan.price}</span>
                <span className="text-sm font-medium text-muted-foreground">{plan.pricePeriod}</span>
              </div>
              <ul className="space-y-3">
                {plan.features.map((feature, index) => (
                  <li key={index} className="flex items-center">
                    <CheckCircle
                      className={`h-5 w-5 mr-2 shrink-0 ${
                        feature.available ? "text-primary" : "text-muted-foreground/50" // Changed from text-green-500 to text-primary for available
                      }`}
                    />
                    <span className={`${!feature.available ? "text-muted-foreground line-through" : "text-foreground"}`}> {/* Ensure available text uses foreground */}
                      {feature.text}
                    </span>
                  </li>
                ))}
              </ul>
            </CardContent>
            <CardFooter className="p-6 bg-muted/30 rounded-b-xl">
              <Button
                className={`w-full text-lg py-3 ${
                  plan.highlight ? "bg-accent hover:bg-accent/90 text-accent-foreground" : ""
                }`}
                size="lg"
                asChild
              >
                <Link href={`/subscribe?plan=${plan.id}`}>{plan.cta}</Link>
              </Button>
            </CardFooter>
          </Card>
        ))}
      </div>

      <div className="mt-16 text-center">
        <p className="text-muted-foreground">
          ¿Necesitas una solución personalizada o tienes preguntas?{" "}
          <Link href="/contact" className="font-medium text-primary hover:underline">
            Contáctanos
          </Link>
        </p>
      </div>
    </div>
  );
}
